Repository UnirCs/DWFS-PER9208-2324, pull requests merged in 2024-04, with the labels that each got.

#18 Merge from Freddy Barragán
  Tema_1/Freddy_Barragan/CV/circle-phone-flip.svg
  Tema_1/Freddy_Barragan/CV/comentario-alt.svg
  Tema_1/Freddy_Barragan/CV/cv.css
  Tema_1/Freddy_Barragan/CV/cv.html
  Tema_1/Freddy_Barragan/CV/en.svg
  Tema_1/Freddy_Barragan/CV/marcador.svg
  Tema_1/Freddy_Barragan/CV/sobre.svg
  Tema_1/Freddy_Barragan/Cinema/cinema.css
  Tema_1/Freddy_Barragan/Cinema/cinema.html
Labels: Se necesitan cambios

#24 Tema 2
  Tema_2/Luis_Miguel_Moncada_Ocampo/cinema/cinema.js
  Tema_2/Luis_Miguel_Moncada_Ocampo/filtros/actividad.js
Labels: Se necesitan cambios

#23 Realización ejercicio del tema 1 del cine
  Tema_1/Maria_Mendez_Garcia/cinema/index.html
  Tema_1/Maria_Mendez_Garcia/cinema/styles.css
Labels: Se necesitan cambios

#34 [TEMA_1] - [TEMA_2] - [TEMA_3] Activities
  Tema_1/Andres-Alexandro-Tapia-Flores/cinema/index.html
  Tema_1/Andres-Alexandro-Tapia-Flores/cinema/style.css
  Tema_1/Andres-Alexandro-Tapia-Flores/cv/index.html
  Tema_1/Andres-Alexandro-Tapia-Flores/cv/picture.jpg
  Tema_1/Andres-Alexandro-Tapia-Flores/cv/style.css
  Tema_2/Andres-Alexandro-Tapia-Flores/cinema/cinema.js
  Tema_2/Andres-Alexandro-Tapia-Flores/filtros/actividad.js
  Tema_3/Andres-Alexandro-Tapia-Flores/chuck/index.html
  Tema_3/Andres-Alexandro-Tapia-Flores/chuck/styles.css
  Tema_3/Andres-Alexandro-Tapia-Flores/cinema/cinema.js
  Tema_3/Andres-Alexandro-Tapia-Flores/cinema/index.html
  Tema_3/Andres-Alexandro-Tapia-Flores/cinema/style.css
Labels: Se necesitan cambios

#32 Ejercicio Tema 2
  Tema_2/Enzo_Torres/ImageHandler.js
  Tema_2/Enzo_Torres/Readme.md
  Tema_2/Enzo_Torres/actividad.js
  Tema_2/Enzo_Torres/input/cat.jpg
  Tema_2/Enzo_Torres/input/dog.jpg
  Tema_2/Enzo_Torres/input/tucan.jpg
  Tema_2/Enzo_Torres/output/ejemplo.jpg
  Tema_2/Enzo_Torres/output/ejemplo1.jpg
  Tema_2/Enzo_Torres/output/expected/merged.jpg
  Tema_2/Enzo_Torres/output/expected/tucan_black_and_white.jpg
  Tema_2/Enzo_Torres/output/expected/tucan_blue.jpg
  Tema_2/Enzo_Torres/output/expected/tucan_dimed.jpg
  Tema_2/Enzo_Torres/output/expected/tucan_green.jpg
  Tema_2/Enzo_Torres/output/expected/tucan_grey.jpg
  Tema_2/Enzo_Torres/output/expected/tucan_inverse.jpg
  Tema_2/Enzo_Torres/output/expected/tucan_red.jpg
  Tema_2/Enzo_Torres/output/expected/tucan_scale_down.jpg
  Tema_2/Enzo_Torres/output/merged.jpg
  Tema_2/Enzo_Torres/output/tucan_black_and_white.jpg
  Tema_2/Enzo_Torres/output/tucan_blue.jpg
  Tema_2/Enzo_Torres/output/tucan_dimed.jpg
  Tema_2/Enzo_Torres/output/tucan_green.jpg
  Tema_2/Enzo_Torres/output/tucan_grey.jpg
  Tema_2/Enzo_Torres/output/tucan_inverse.jpg
  Tema_2/Enzo_Torres/output/tucan_red.jpg
  Tema_2/Enzo_Torres/output/tucan_scale_down.jpg
  Tema_2/Enzo_Torres/output/tucan_scale_down_bad.jpg
Labels: PR Incorrecta

#40 Añade ejercicios Tema 2
  Tema_2/Ignacio_Gonzalez_Diaz-Tendero/Cinema/cinema.js
  Tema_2/Ignacio_Gonzalez_Diaz-Tendero/Filtros/actividad.js
Labels: Se necesitan cambios

#41 Ejercicios tema 2 - corregido
  Tema_2/Juan_Aguilar_Abanto/cinema/cinema.js
  Tema_2/Juan_Aguilar_Abanto/filtros/ImageHandler.js
  Tema_2/Juan_Aguilar_Abanto/filtros/actividad.js
  Tema_2/Juan_Aguilar_Abanto/filtros/input/cat.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/input/dog.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/input/tucan.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/ejemplo.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/expected/merged.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/expected/tucan_black_and_white.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/expected/tucan_blue.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/expected/tucan_dimed.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/expected/tucan_green.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/expected/tucan_grey.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/expected/tucan_inverse.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/expected/tucan_red.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/expected/tucan_scale_down.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/merged.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/tucan_black_and_white.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/tucan_blue.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/tucan_dimed.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/tucan_green.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/tucan_grey.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/tucan_inverse.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/tucan_red.jpg
  Tema_2/Juan_Aguilar_Abanto/filtros/output/tucan_scale_down.jpg
Labels: Se necesitan cambios

#46 Desarrollo ejercicios Tema 1, Ej1: CV y Ej2:Cinema
  Tema_1/Diego_Rueda/ej1_cv/Fotografia.jpg
  Tema_1/Diego_Rueda/ej1_cv/index.html
  Tema_1/Diego_Rueda/ej1_cv/styles.css
  Tema_1/Diego_Rueda/ej2_cinema/ejemplo_cine.png
  Tema_1/Diego_Rueda/ej2_cinema/ejemplo_cine2.jpg
  Tema_1/Diego_Rueda/ej2_cinema/index.html
  Tema_1/Diego_Rueda/ej2_cinema/styles.css
Labels: Se necesitan cambios

#47 Realización de los ejercicios del tema 2
  Tema_2/Maria_Alejandra_Mendez_Garcia/cinema/cinema.js
  Tema_2/Maria_Alejandra_Mendez_Garcia/filtros/actividad.js
Labels: Se necesitan cambios

#36 Cinema y filtros Freddy Barragán
  Tema_2/Freddy_Barragan/cinema.js
  Tema_2/Freddy_Barragan/filtros/ImageHandler.js
  Tema_2/Freddy_Barragan/filtros/Readme.md
  Tema_2/Freddy_Barragan/filtros/actividad.js
  Tema_2/Freddy_Barragan/filtros/input/cat.jpg
  Tema_2/Freddy_Barragan/filtros/input/dog.jpg
  Tema_2/Freddy_Barragan/filtros/input/tucan.jpg
  Tema_2/Freddy_Barragan/filtros/output/ejemplo.jpg
  Tema_2/Freddy_Barragan/filtros/output/expected/merged.jpg
  Tema_2/Freddy_Barragan/filtros/output/expected/tucan_black_and_white.jpg
  Tema_2/Freddy_Barragan/filtros/output/expected/tucan_blue.jpg
  Tema_2/Freddy_Barragan/filtros/output/expected/tucan_dimed.jpg
  Tema_2/Freddy_Barragan/filtros/output/expected/tucan_green.jpg
  Tema_2/Freddy_Barragan/filtros/output/expected/tucan_grey.jpg
  Tema_2/Freddy_Barragan/filtros/output/expected/tucan_inverse.jpg
  Tema_2/Freddy_Barragan/filtros/output/expected/tucan_red.jpg
  Tema_2/Freddy_Barragan/filtros/output/expected/tucan_scale_down.jpg
  Tema_2/Freddy_Barragan/filtros/output/merged.jpg
  Tema_2/Freddy_Barragan/filtros/output/tucan_black_and_white.jpg
  Tema_2/Freddy_Barragan/filtros/output/tucan_blue.jpg
  Tema_2/Freddy_Barragan/filtros/output/tucan_dimed.jpg
  Tema_2/Freddy_Barragan/filtros/output/tucan_green.jpg
  Tema_2/Freddy_Barragan/filtros/output/tucan_grey.jpg
  Tema_2/Freddy_Barragan/filtros/output/tucan_inverse.jpg
  Tema_2/Freddy_Barragan/filtros/output/tucan_red.jpg
  Tema_2/Freddy_Barragan/filtros/output/tucan_scale_down.jpg
  Tema_3/Freddy_Barragan/chuck/index.html
  Tema_3/Freddy_Barragan/chuck/styles.css
  Tema_3/Freddy_Barragan/cinema/cinema.js
  Tema_3/Freddy_Barragan/cinema/index.html
  Tema_3/Freddy_Barragan/cinema/styles.css
Labels: PR Incorrecta

#57 Actividad 2 cinema y filtros
  Tema_1/Cristian_De_La_Cruz_Mendoza/CV/Cristiano.png
  Tema_1/Cristian_De_La_Cruz_Mendoza/CV/index.html
  Tema_1/Cristian_De_La_Cruz_Mendoza/CV/styles.css
  Tema_1/Cristian_De_La_Cruz_Mendoza/Cinema/index.html
  Tema_1/Cristian_De_La_Cruz_Mendoza/Cinema/styles.css
  Tema_2/Cristian_De_La_Cruz_Mendoza/cinema/cinema.js
  Tema_2/Cristian_De_La_Cruz_Mendoza/filtros/actividad.js
  Tema_3/Cristian_De_La_Cruz_mendoza/chuck/index.html
  Tema_3/Cristian_De_La_Cruz_mendoza/chuck/styles.css
  Tema_3/Cristian_De_La_Cruz_mendoza/cinema/cinema.js
  Tema_3/Cristian_De_La_Cruz_mendoza/cinema/index.html
  Tema_3/Cristian_De_La_Cruz_mendoza/cinema/styles.css
Labels: Se necesitan cambios

#83 Tema 2 - Cinema
  Tema_1/Camilo_Valencia/CV/index.html
  Tema_1/Camilo_Valencia/CV/style.css
  Tema_2/Camilo_Valencia/cinema/cinema.js
Labels: Se necesitan cambios

#87 ejercicio cinema tema 2
  Tema_2/Xavier_Antonio_Quevedo_Jumbo/cinema/cinema.js
  Tema_3/Xavier_Antonio_Quevedo_Jumbo/chuck/index.html
  Tema_3/Xavier_Antonio_Quevedo_Jumbo/chuck/styles.css
Labels: Se necesitan cambios

#75 Tema 2 Filtros y Cinema
  Tema_2/Christian_David_Viracocha_Suntaxi/Cinema/cinema.js
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/ImageHandler.js
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/Readme.md
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/actividad.js
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/input/cat.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/input/dog.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/input/tucan.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/input/tucan0.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/ejemplo.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/expected/merged.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/expected/tucan_black_and_white.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/expected/tucan_blue.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/expected/tucan_dimed.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/expected/tucan_green.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/expected/tucan_grey.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/expected/tucan_inverse.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/expected/tucan_red.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/expected/tucan_scale_down.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/merged.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/tucan_black_and_white.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/tucan_blue.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/tucan_dimed.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/tucan_green.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/tucan_grey.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/tucan_inverse.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/tucan_red.jpg
  Tema_2/Christian_David_Viracocha_Suntaxi/filtros/output/tucan_scale_down.jpg
  Tema_3/Christian_David_Viracocha_Suntaxi/chuck/index.html
  Tema_3/Christian_David_Viracocha_Suntaxi/chuck/style.css
  Tema_3/Christian_David_Viracocha_Suntaxi/cinema/cinema.js
  Tema_3/Christian_David_Viracocha_Suntaxi/cinema/index.html
  Tema_3/Christian_David_Viracocha_Suntaxi/cinema/styles.css
Labels: Se necesitan cambios

#71 Tema_1 CV y Cinema
  Tema_1/John_Jairo_Roa_Castaneda/CV/Index.html
  Tema_1/John_Jairo_Roa_Castaneda/CV/css/Index.css
  Tema_1/John_Jairo_Roa_Castaneda/CV/recursos/iconos/email.png
  Tema_1/John_Jairo_Roa_Castaneda/CV/recursos/iconos/map.png
  Tema_1/John_Jairo_Roa_Castaneda/CV/recursos/iconos/phone.png
  Tema_1/John_Jairo_Roa_Castaneda/CV/recursos/img/imgJohnRoa.JPG
  Tema_1/John_Jairo_Roa_Castaneda/Cinema/Index.html
  Tema_1/John_Jairo_Roa_Castaneda/Cinema/css/Index.css
  Tema_1/John_Jairo_Roa_Castaneda/Cinema/recursos/iconos/favicon.ico
  Tema_2/John_Jairo_Roa_Castaneda/cinema/cinema.js
  Tema_2/John_Jairo_Roa_Castaneda/filtros/actividad.js
  Tema_3/John_Jairo_Roa_Castaneda/Cinema/Index.html
  Tema_3/John_Jairo_Roa_Castaneda/Cinema/css/Index.css
  Tema_3/John_Jairo_Roa_Castaneda/Cinema/js/cinema.js
  Tema_3/John_Jairo_Roa_Castaneda/Cinema/recursos/iconos/favicon.ico
  Tema_3/John_Jairo_Roa_Castaneda/chuck/Index.html
  Tema_3/John_Jairo_Roa_Castaneda/chuck/css/styles.css
  Tema_3/John_Jairo_Roa_Castaneda/chuck/recursos/iconos/favicon.ico
Labels: Se necesitan cambios

#95 Tareas José Toledo
  Tema_2/Jose_Roberto_Toledo_Illescas/cinema/cinema.js
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/ImageHandler.js
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/actividad.js
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/input/cat.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/input/dog.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/input/tucan.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/black_and_white.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/blue.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/dimed.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/ejemplo.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/expected/merged.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/expected/tucan_black_and_white.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/expected/tucan_blue.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/expected/tucan_dimed.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/expected/tucan_green.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/expected/tucan_grey.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/expected/tucan_inverse.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/expected/tucan_red.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/expected/tucan_scale_down.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/green.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/grey.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/inverse.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/merged.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/red.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/scale_down.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/output/tucan_grey.jpg
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/package-lock.json
  Tema_2/Jose_Roberto_Toledo_Illescas/filtros/package.json
  Tema_3/Jose_Roberto_Toledo_Illescas/Cinema/cinema.js
  Tema_3/Jose_Roberto_Toledo_Illescas/Cinema/index.html
  Tema_3/Jose_Roberto_Toledo_Illescas/Cinema/style.css
  Tema_3/Jose_Roberto_Toledo_Illescas/chuck/chuck.gif
  Tema_3/Jose_Roberto_Toledo_Illescas/chuck/index.html
  Tema_3/Jose_Roberto_Toledo_Illescas/chuck/styles.css
  Tema_4/Jose_Roberto_Toledo_Illescas/cinema/cinema.css
  Tema_4/Jose_Roberto_Toledo_Illescas/cinema/cinema.html
  Tema_4/Jose_Roberto_Toledo_Illescas/cinema/cinema.js
  Tema_4/Jose_Roberto_Toledo_Illescas/cinema/registro.css
  Tema_4/Jose_Roberto_Toledo_Illescas/cinema/registro.html
  Tema_4/Jose_Roberto_Toledo_Illescas/cinema/registro.js
Labels: Se necesitan cambios

#80 Tema 2 - cinema y Filtros
  Tema_2/Mario_Andres_Barzola_Vera/cinema/cinema.js
  Tema_2/Mario_Andres_Barzola_Vera/filtros/actividad.js
Labels: Propuesta de mejora
