Repository UnirCs/DWFS-PER9208-2324, pull requests merged in 2024-05, with the labels that each got.

#131 Tema 5
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/.gitignore
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/README.md
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/package-lock.json
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/package.json
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/public/favicon.ico
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/public/index.html
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/public/logo192.png
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/public/logo512.png
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/public/manifest.json
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/public/robots.txt
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/src/components/Footer.js
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/src/components/Header.js
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/src/components/Movie.js
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/src/index.js
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/src/movies.js
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/src/reportWebVitals.js
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/src/setupTests.js
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/src/styles/footer.css
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/src/styles/header.css
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/src/styles/index.css
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/src/styles/movie.css
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/src/views/MovieList.js
  Tema_5/Jose_Alejandro_Alvarez_Mendoza/movies/urlVercel.txt
Labels: Se necesitan cambios

#148 Actividad Tema 6
  Tema_6/Cristian_De_La_Cruz_Mendoza/calculadora.md
  Tema_6/Cristian_De_La_Cruz_Mendoza/cinema.md
  Tema_6/Cristian_De_La_Cruz_Mendoza/hunde_la_flota.md
Labels: Se necesitan cambios, Propuesta de mejora

#144 Añade ejercicios tema 6
  Tema_6/Ignacio_Gonzalez_Diaz-Tendero/Calculadora.md
  Tema_6/Ignacio_Gonzalez_Diaz-Tendero/Hundir_flota.md
  Tema_6/Ignacio_Gonzalez_Diaz-Tendero/Reserva_butacas.md
Labels: Se necesitan cambios

#134 Tema 6 - Juan Maximiliano Aguilar Abanto
  Tema_6/Juan_Maximiliano_Aguilar_Abanto/API_Calculadora.md
  Tema_6/Juan_Maximiliano_Aguilar_Abanto/Hunde_La_Flota.md
  Tema_6/Juan_Maximiliano_Aguilar_Abanto/Reserva_Butacas_Cine.md
Labels: Se necesitan cambios

#139 practicas 1 2 3
  Tema_1/Efrain_Diaz/cinema/index.html
  Tema_1/Efrain_Diaz/cinema/styles.css
  Tema_1/Efrain_Diaz/cv/index.html
  Tema_1/Efrain_Diaz/cv/styles.css
  Tema_1/Efrain_Diaz/cv/superman.png
  Tema_2/Efrain_diaz/cinema/cinema.js
  Tema_2/Efrain_diaz/filtros/actividad.js
  Tema_3/Efrain_Diaz/chuck/index.html
Labels: PR Incorrecta
